name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust-impl -> target"

      - name: Check code formatting
        run: cargo fmt --manifest-path rust-impl/Cargo.toml --all -- --check

      - name: Check build
        run: cargo check --manifest-path rust-impl/Cargo.toml --all-targets

      - name: Run unit tests
        run: cargo test --manifest-path rust-impl/Cargo.toml --lib

      - name: Run doc tests
        run: cargo test --manifest-path rust-impl/Cargo.toml --doc
